# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow, QFileDialog, QMessageBox
import webbrowser
import sys

class Window2(QMainWindow):
    def __init__(self, parent=None):
        super(). __init__(parent)
        self.setWindowTitle('Window2')
        self.resize(400, 500)
        self.text_edit = QtWidgets.QTextEdit(self)
        self.text_edit.setGeometry(QtCore.QRect(10, 10, 381, 421))
        self.btn_1 = QtWidgets.QPushButton(self)
        self.btn_1.setGeometry(QtCore.QRect(190, 450, 93, 28))
        self.btn_1.setText("Save")
        self.btn_2 = QtWidgets.QPushButton(self)
        self.btn_2.setGeometry(QtCore.QRect(290, 450, 93, 28))
        self.btn_2.setText("Cancel")
        self.btn_3 = QtWidgets.QPushButton(self)
        self.btn_3.setGeometry(QtCore.QRect(90, 450, 93, 28))
        self.btn_3.setText('Open')

        self.btn_1.clicked.connect(self.action_clicked)
        self.btn_2.clicked.connect(self.w_end)
        self.btn_3.clicked.connect(self.action_open)

    @QtCore.pyqtSlot()
    def action_clicked(self):
        action = self.sender()
        if action.text() == 'Save':
            fname = QFileDialog.getSaveFileName(self)[0]

            try:
                f = open(fname, 'w')
                text = self.text_edit.toPlainText()
                f.write(text)
                f.close()
            except FileNotFoundError:
                print('File not found')

    @QtCore.pyqtSlot()
    def action_open(self):
        action = self.sender()
        if action.text() == 'Open':
            fname = QFileDialog.getOpenFileName(self)[0]

            try:
                f = open(fname, 'r')
                data = f.read()
                self.text_edit.setText(data)

                f.close()

            except FileNotFoundError:
                print('File not found')

    def w_end(self):
        self.hide()

class Window(QMainWindow):
    def __init__(self):
        super(Window, self). __init__()
        self.setWindowTitle("Window")
        self.resize(400, 500)
        self.verticalLayoutWidget = QtWidgets.QWidget(self)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 250, 381, 241))
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_1 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_1.setText("Notes")
        self.verticalLayout.addWidget(self.btn_1)
        self.btn_3 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_3.setText("Web search")
        self.verticalLayout.addWidget(self.btn_3)
        self.label = QtWidgets.QLabel(self)
        self.label.setGeometry(QtCore.QRect(10, 10, 381, 231))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../../PycharmProjects/NoteMaker/pic/1837319.jpg"))
        self.label.setObjectName("label")

        self.btn_1.clicked.connect(self.create_window)
        self.btn_3.clicked.connect(self.open_search)

    def create_window(self):
        self.Window = Window2(self)
        self.Window.show()

    def open_search(url):
        webbrowser.open('https://www.google.com')

def application():
    app = QtWidgets.QApplication(sys.argv)
    window = Window()
    window.show()

    sys.exit(app.exec())

if __name__ == "__main__":
    application()
